# Generated by Django 2.0.2 on 2018-03-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themes',
            old_name='desc',
            new_name='description',
        ),
    ]
